### PR TITLE
Update blacklist.txt

### PR DESCRIPTION
**Pull request by vuolter**

### CODE REVIEW

**Comment by GammaC0de** [comment]
@vuolter / @stickell Please merge..

**Comment by vuolter** [comment]
@GammaC0de I can't. We have to wait @stickell .

**Comment by GammaC0de** [comment]
Is he Ok?
last time that he was online was on the 3rd of august..

Is he responsible of http://pyload.org/download also?

**Comment by vuolter** [comment]
For http://pyload.org/download is @RaNaN

**Comment by stickell** [comment]
Sorry guys I missed this.
I'm still following updates by email every day but I have no more time to work on the project

**Comment by GammaC0de** [comment]
:+1:

**Pull request merged**
